
API_key: "ee204058-084f-41bf-9325-7e469cbe0eb0"
host: scmb-ckan.its.hpc.net.uq.edu.au
organization: "mduq"
trajectory_data_path: /home/s4536542/PycharmProjects/ATB_repo/trajectory_data
public_data_path: /home/s4536542/PycharmProjects/ATB_repo/public_data
public_hostname: scmb-ckan.its.hpc.net.uq.edu.au
