
API_key: "ee204058-084f-41bf-9325-7e469cbe0eb0"
host: molecular-dynamics.atb.uq.edu.au
organization: "mduq"
trajectory_data_path: /home/atb/atb_repo/trajectory_data #../trajectory_data
public_data_path: /home/atb/atb_repo/public_data #../public_data
public_hostname: molecular-dynamics.atb.uq.edu.au
